### ISSUE TITLE
Responsive ness on phone

### ISSUE THREAD

**Issue by Insticthere** [verlox/Verlox.cc-Site#1]
the particle background on small size is broken you can fix it i think something is blocking it by being in front or the js is being broken.

also we are very same i am destroying people since 17 too and i hate kpop too nice site will copy the idea👍

what do u mean by lithium tho?

**Comment by verlox** [comment]
ill check it out later if i get a chance

lithium is a discord server nuker i made, its pinned on my profile

**Comment by Insticthere** [comment]
i see fine then
